// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
import MapController from "./map_controller"
import MapEditorController from "./map_editor_controller"
import FileInputController from "./file_input_controller"

application.register("file_input", FileInputController)
application.register("map", MapController)
application.register("map_editor", MapEditorController)
